apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org.directory
    email: teste@gmail.com
    privateKeySecretRef:
      name: letsencrypt-tls
    solver:
      - http01:
          ingress:
            class: nginx
