apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "gabrielggs/hellogo:v6.8"
          
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.06"
            limits:
              memory: "556Mi"
              cpu: "0.06"
              
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            # initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            # initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: "goserver-env"
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volumepvc
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: "goserver-env"
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: "goserver-env"
          #         key: AGE
      volumes:
        - name: goserver-volumepvc
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: goserver-family
            items:
            - key: members
              path: "family.txt"
