# Iniciando uma imagem base nginx
FROM nginx

# Definindo versao dockerize
ENV DOCKERIZE_VERSION=v0.7.0

# Rodando instalacao dockerize
RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

# Copiando arquivo de configuracao do server nginx
COPY default.conf /etc/nginx/conf.d/default.conf